### PR TITLE
Remove atoms per ionic unit multiplier for all atomic density calculations; fix print for py3

### PR DESCRIPTION
**Pull request by cseal6**

### CODE REVIEW

**Comment by gridley** [comment]
Hey @cseal6, do you have any proof that this works? I think the calculation there makes sense. You take density, then consider one ionic unit's molar mass, which, for ThF4 is about 232+4*19 g / mol. So, for Gd, for example:

<pre>
In [1]: import RefuelCore

In [2]: gd = RefuelCore.SerpentMaterial('GdF3')

In [3]: print(gd)
Material name: GdF3
Atom Density: 0.05987080191026679
Mass Density: 7.1
Temperature: None
Burnable: No
Volume: None
 ----------- Isotopics: --------------
9019   |   0.2660252822459259
64156   |   0.15024462472425898
64154   |   0.016000648847038817
64157   |   0.11486704332851261
64152   |   0.0014679494355081485
64158   |   0.18231931989011205
64160   |   0.1604468733010406
64155   |   0.10862825822760297
</pre>

Which gives  a quite reasonable atom density. These are almost always from 0.01-0.1 atom/cmb.

Same goes for the ThF4 mixture maker you changed:

<pre>
In [3]: print(thf4)
Material name: ThF4
Atom Density: 0.06158230449289813
Mass Density: 6.3
Temperature: None
Burnable: No
Volume: None
 ----------- Isotopics: --------------
9019   |   0.8
90232   |   0.2
</pre>

Although, there's definite something weird going on with the FLiBe. This atom density is way too high. This is the root of your all's problems.

<pre>
In [5]: print(flibe)
Material name: None
Atom Density: 0.1960661925907159
Mass Density: 1.94
Temperature: None
Burnable: No
Volume: None
 ----------- Isotopics: --------------
9019   |   1.1800000000000002
3007   |   0.819959
3006   |   4.099999999999548e-05
4009   |   0.18000000000000005
</pre>

I think the problem's on line 830. The molar mass of LiFBeF2 should be around 73 g / mol, but it's coming out at around 30 g / mol. This is the root of the problems. I looked into this some, and it comes from me mixing up weight and atom fractions of BeF2 / LiF. Looking at [this phase diagram](http://heatandmass.ep.wisc.edu/) from UW Madison, you can see that the MOLE fraction of BeF2 should be just over 0.5. Instead, I accidentally put this at 0.18. I'm not sure what the optimal mole fraction of BeF2 is just from looking at the graph though. This would be worth looking at. I'd bet the density data I pulled refers to a perfect 50/50 BeF2/LiF mix.

So, I'll leave this for you to fix, since it should be a breeze.

**Comment by cseal6** [comment]
@gridley Just from unit analysis, I don't think that multiplying the atom density by atoms/ionic unit is necessary.

In ORNL 7207, they use a mol-% very close to what you're using, so I don't think your molar mass is incorrect unless current MSR design now calls for 50 mol-%. The LiF and BeF2 are not present in equal amounts, so the molar mass of the mix should not be 73 g.

I'll look more into the density value. Thanks for your time and help on this.

**Comment by cseal6** [comment]
@gridley Alright, I found where I made a mistake in my unit analysis, and we definitely need a multiplier. It looks we should use 2.18 instead of 5 for the 0.82LiF-0.18BeF2 mix since we're using the weighted average of each ion group's mass to compute the average molar mass of the mix. The weighted average number of atoms per ion group is 2.18. 

If that makes sense to you, I'll fix my changes and resubmit this request.

**Comment by gridley** [comment]
Yeah, that makes a lot of sense. When you make the changes, it would be good to have that 2.18 number be calculated. Thanks for contributing to the code! This project will probably be quite interesting when you guys get some results.

Oh, and by the way, if you just push your changes to your repo forks's master branch, you will not need to resubmit the pull request. Git is confusing at first, sorry to have you guys deal with it. It's really convenient once you get the lingo though.

**Comment by cseal6** [comment]
Thanks for that. Saved me some time. Here's the PuF3 LiF-BeF2 mixed at the same fraction (0.01 PuF3) that you sent on slack, so it has more than halved it:

```
Material name: newmix
Atom Density: 0.08486650194763949
Mass Density: 0.0
Temperature: None
Burnable: No
Volume: None
 ----------- Isotopics: --------------
31069   |   1.1878265046283128e-06
3007   |   0.03183171536367718
31071   |   1.1878265046283128e-06
3006   |   1.5916653514512563e-06
94239   |   5.36028005699225e-05
4009   |   0.006987799103933117
94240   |   3.4438153002817977e-06
9019   |   0.045985973545798295

```

**Comment by gridley** [comment]
Beautiful! PR accepted!

**Pull request merged**
